<?php

    return [
        "modalidades" => [
            0 => "Acadêmico",
            1 => "Efetivo",
            2 => "Fundador",
            3 => "Honorário"
        ],
        'titulis' => [
            "Agrimensor(a)",
            "Arquiteto(a) e Urbanista",
            "Engenheiro(a) Acústico",
            "Engenheiro(a) Aeroespacial",
            "Engenheiro(a) Aeronáutico",
            "Engenheiro(a) Aeronáutico e Espaço",
            "Engenheiro(a) Agrícola",
            "Engenheiro(a) Agrícola e Ambiental",
            "Engenheiro(a) Agrimensor",
            "Engenheiro(a) Agrimensor e Cartógrafo",
            "Engenheiro(a) Agroindustrial",
            "Engenheiro(a) Agroindustrial Agroquímica",
            "Engenheiro(a) Agrônomo",
            "Engenheiro(a) Ambiental",
            "Engenheiro(a) Ambiental e da Sustentabilidade",
            "Engenheiro(a) Ambiental e Energias Renováveis",
            "Engenheiro(a) Ambiental e Sanitarista",
            "Engenheiro(a) Ambiental e Urbana",
            "Engenheiro(a) Automotivo",
            "Engenheiro(a) Biomédico",
            "Engenheiro(a) Bioquímico",
            "Engenheiro(a) Cartógrafo",
            "Engenheiro(a) Cartógrafo e Agrimensor",
            "Engenheiro(a) Civil",
            "Engenheiro(a) Civil Costeiro e Portuário",
            "Engenheiro(a) Civil da Mobilidade",
            "Engenheiro(a) Civil de Infraestrutura",
            "Engenheiro(a) Civil e Ambiental",
            "Engenheiro(a) Civil Empresarial",
            "Engenheiro(a) Computacional",
            "Engenheiro(a) de Agronegócios",
            "Engenheiro(a) de Alimentos",
            "Engenheiro(a) de Aqüicultura",
            "Engenheiro(a) de Aqüicultura e Recursos Hídricos",
            "Engenheiro(a) de Automação",
            "Engenheiro(a) de Automação e Controle",
            "Engenheiro(a) de Automação Empresarial",
            "Engenheiro(a) de Automação Industrial",
            "Engenheiro(a) de Bioenergia",
            "Engenheiro(a) de Bioprocessos",
            "Engenheiro(a) de Bioprocessos e Biotecnologia",
            "Engenheiro(a) de Biotecnologia",
            "Engenheiro(a) de Biotecnologia e Bioprocessos",
            "Engenheiro(a) de Computação",
            "Engenheiro(a) de Computação e Informação",
            "Engenheiro(a) de Comunicações",
            "Engenheiro(a) de Controle e Automação",
            "Engenheiro(a) de Controle e Automação de Processos",
            "Engenheiro(a) de Energia",
            "Engenheiro(a) de Energias",
            "Engenheiro(a) de Energias Renováveis",
            "Engenheiro(a) de Exploração e Produção de Petróleo",
            "Engenheiro(a) de Fortificação e Construção",
            "Engenheiro(a) de Geodésia",
            "Engenheiro(a) de Gestão de Energia",
            "Engenheiro(a) de Infra-Estrutura Aeronáutica",
            "Engenheiro(a) de Instrumentação, Automação e Robótica",
            "Engenheiro(a) de Materiais",
            "Engenheiro(a) de Materiais e Manufatura",
            "Engenheiro(a) de Materiais e Nanotecnologia",
            "Engenheiro(a) de Minas",
            "Engenheiro(a) de Minas e Meio Ambiente",
            "Engenheiro(a) de Operação - Aeronáutica",
            "Engenheiro(a) de Operação - Construção Civil",
            "Engenheiro(a) de Operação - Construção de Estradas",
            "Engenheiro(a) de Operação - Edificações",
            "Engenheiro(a) de Operação - Eletrônica",
            "Engenheiro(a) de Operação - Eletrotécnica",
            "Engenheiro(a) de Operação - Estradas",
            "Engenheiro(a) de Operação - Fabricação Mecânica",
            "Engenheiro(a) de Operação - Indústria da Madeira",
            "Engenheiro(a) de Operação - Máquinas e Motores",
            "Engenheiro(a) de Operação - Mecânica",
            "Engenheiro(a) de Operação - Mecânica Automobilística",
            "Engenheiro(a) de Operação - Mecânica de Manutenção",
            "Engenheiro(a) de Operação - Mecânica de Máquinas e Ferramentas",
            "Engenheiro(a) de Operação - Metalurgista",
            "Engenheiro(a) de Operação - Petroquímica",
            "Engenheiro(a) de Operação - Processo de Fabricação Mecânica",
            "Engenheiro(a) de Operação - Produção",
            "Engenheiro(a) de Operação - Química",
            "Engenheiro(a) de Operação - Refrigeração e Ar Condicionado",
            "Engenheiro(a) de Operação - Siderurgia",
            "Engenheiro(a) de Operação - Telecomunicações",
            "Engenheiro(a) de Operação - Têxtil",
            "Engenheiro(a) de Pesca",
            "Engenheiro(a) de Petróleo",
            "Engenheiro(a) de Plástico",
            "Engenheiro(a) de Produção",
            "Engenheiro(a) de Produção - Agroindústria",
            "Engenheiro(a) de Produção - Civil",
            "Engenheiro(a) de Produção - Eletricista",
            "Engenheiro(a) de Produção - Materiais",
            "Engenheiro(a) de Produção - Mecânica",
            "Engenheiro(a) de Produção - Metalurgista",
            "Engenheiro(a) de Produção - Química",
            "Engenheiro(a) de Produção - Têxtil",
            "Engenheiro(a) de Produção e Qualidade",
            "Engenheiro(a) de Produção e Sistemas",
            "Engenheiro(a) de Saúde e Segurança",
            "Engenheiro(a) de Segurança do Trabalho",
            "Engenheiro(a) de Software",
            "Engenheiro(a) de Telecomunicações",
            "Engenheiro(a) de Transmissão",
            "Engenheiro(a) de Transporte e Logística",
            "Engenheiro(a) de Transportes",
            "Engenheiro(a) de Transportes e Logística",
            "Engenheiro(a) Eletricista",
            "Engenheiro(a) Eletricista - Eletrônica",
            "Engenheiro(a) Eletricista - Eletrotécnica",
            "Engenheiro(a) Eletricista – Energia",
            "Engenheiro(a) Eletricista - Robótica e Automação Industrial",
            "Engenheiro(a) Eletricista - Telecomunicações",
            "Engenheiro(a) Eletricista e Eletrônico",
            "Engenheiro(a) em Eletrônica",
            "Engenheiro(a) em Eletrônica e de Computação",
            "Engenheiro(a) em Eletrônica e de Telecomunicações",
            "Engenheiro(a) em Eletrotécnica",
            "Engenheiro(a) em Topografia Rural",
            "Engenheiro(a) Ferroviário e de Logística",
            "Engenheiro(a) Ferroviário e Metroviário",
            "Engenheiro(a) Físico",
            "Engenheiro(a) Florestal",
            "Engenheiro(a) Geógrafo",
            "Engenheiro(a) Geólogo",
            "Engenheiro(a) Hídrico",
            "Engenheiro(a) Industrial - Civil",
            "Engenheiro(a) Industrial - Elétrica",
            "Engenheiro(a) Industrial - Eletrônica",
            "Engenheiro(a) Industrial - Eletrotécnica",
            "Engenheiro(a) Industrial - Madeira",
            "Engenheiro(a) Industrial - Mecânica",
            "Engenheiro(a) Industrial - Metalurgia",
            "Engenheiro(a) Industrial - Química",
            "Engenheiro(a) Industrial - Telecomunicações",
            "Engenheiro(a) Industrial Madeireiro",
            "Engenheiro(a) Mecânico",
            "Engenheiro(a) Mecânico - Automação e Sistemas",
            "Engenheiro(a) Mecânico Aeronáutico",
            "Engenheiro(a) Mecânico Automotivo",
            "Engenheiro(a) Mecânico e de Armamento",
            "Engenheiro(a) Mecânico e de Automóvel",
            "Engenheiro(a) Mecânico Eletricista",
            "Engenheiro(a) Mecânico Empresarial",
            "Engenheiro(a) Mecânico Naval",
            "Engenheiro(a) Mecatrônico",
            "Engenheiro(a) Metalurgista",
            "Engenheiro(a) Militar",
            "Engenheiro(a) Naval",
            "Engenheiro(a) Naval e Oceânico",
            "Engenheiro(a) Nuclear",
            "Engenheiro(a) Químico",
            "Engenheiro(a) Sanitarista",
            "Engenheiro(a) Sanitarista e Ambiental",
            "Engenheiro(a) Têxtil",
            "Engenheiro(a) Topógrafo",
            "Geógrafo(a)",
            "Geólogo(a)",
            "Meteorologista",
            "Técnico(a) de Segurança do Trabalho",
            "Tecnólogo(a) de Minas",
            "Tecnólogo(a) de Segurança do Trabalho",
            "Tecnólogo(a) em Açúcar e Álcool",
            "Tecnólogo(a) em Administração Rural",
            "Tecnólogo(a) em Aeronaves",
            "Tecnólogo(a) em Agricultura",
            "Tecnólogo(a) em Agrimensura",
            "Tecnólogo(a) em Agroecologia",
            "Tecnólogo(a) em Agroindústria",
            "Tecnólogo(a) em Agronegócios",
            "Tecnólogo(a) em Agronomia",
            "Tecnólogo(a) em Agropecuária",
            "Tecnólogo(a) em Agropecuária Integrada",
            "Tecnólogo(a) em Alimentos",
            "Tecnólogo(a) em Aqüicultura",
            "Tecnólogo(a) em Automação e Manufatura Digital",
            "Tecnólogo(a) em Automação Industrial",
            "Tecnólogo(a) em Biocombustíveis",
            "Tecnólogo(a) em Bovinocultura",
            "Tecnólogo(a) em Cafeicultura",
            "Tecnólogo(a) em Cerâmica",
            "Tecnólogo(a) em Ciências Agrárias",
            "Tecnólogo(a) em Comunicações Digitais",
            "Tecnólogo(a) em Construção Civil",
            "Tecnólogo(a) em Construção Civil - Edificações",
            "Tecnólogo(a) em Construção Civil - Estrada e Topografia",
            "Tecnólogo(a) em Construção Civil - Movimento de Terra e Pavimentação",
            "Tecnólogo(a) em Construção Civil - Obras de Solos",
            "Tecnólogo(a) em Construção Civil - Obras Hidráulicas",
            "Tecnólogo(a) em Construção Civil - Terraplenagem",
            "Tecnólogo(a) em Construção de Edifícios",
            "Tecnólogo(a) em Construção Naval",
            "Tecnólogo(a) em Controle Ambiental",
            "Tecnólogo(a) em Controle de Obras",
            "Tecnólogo(a) em Cooperativismo",
            "Tecnólogo(a) em Curtumes e Tanantes",
            "Tecnólogo(a) em Design de Interiores",
            "Tecnólogo(a) em Distribuição de Energia Elétrica",
            "Tecnólogo(a) em Edificações",
            "Tecnólogo(a) em Eletricidade",
            "Tecnólogo(a) em Eletromecânica",
            "Tecnólogo(a) em Eletromecânica",
            "Tecnólogo(a) em Eletrônica",
            "Tecnólogo(a) em Eletrônica Automotiva",
            "Tecnólogo(a) em Eletrônica Industrial",
            "Tecnólogo(a) em Eletrotécnica",
            "Tecnólogo(a) em Eletrotécnica Industrial",
            "Tecnólogo(a) em Energias Renováveis",
            "Tecnólogo(a) em Estradas",
            "Tecnólogo(a) em Fabricação Mecânica",
            "Tecnólogo(a) em Fitotecnia",
            "Tecnólogo(a) em Fruticultura",
            "Tecnólogo(a) em Fruticultura de Clima Temperado",
            "Tecnólogo(a) em Geologia",
            "Tecnólogo(a) em Geoprocessamento",
            "Tecnólogo(a) em Gestão Ambiental",
            "Tecnólogo(a) em Gestão da Produção Industrial",
            "Tecnólogo(a) em Gestão da Qualidade",
            "Tecnólogo(a) em Gestão de Cooperativas",
            "Tecnólogo(a) em Gestão de Recursos Hídricos",
            "Tecnólogo(a) em Gestão de Resíduos de Saúde",
            "Tecnólogo(a) em Gestão de Resíduos Sólidos",
            "Tecnólogo(a) em Gestão de Telecomunicações",
            "Tecnólogo(a) em Heveicultura",
            "Tecnólogo(a) em Hidráulica e Saneamento Ambiental",
            "Tecnólogo(a) em Horticultura",
            "Tecnólogo(a) em Indústria da Madeira",
            "Tecnólogo(a) em Indústria Têxtil",
            "Tecnólogo(a) em Instrumentação e Controle",
            "Tecnólogo(a) em Irrigação e Drenagem",
            "Tecnólogo(a) em Laticínios",
            "Tecnólogo(a) em Manufatura Aeronáutica",
            "Tecnólogo(a) em Manutenção de Aeronaves",
            "Tecnólogo(a) em Manutenção de Máquinas e Equipamentos",
            "Tecnólogo(a) em Manutenção Industrial",
            "Tecnólogo(a) em Manutenção Petroquímica",
            "Tecnólogo(a) em Máquinas",
            "Tecnólogo(a) em Máquinas e Equipamentos",
            "Tecnólogo(a) em Máquinas Elétricas",
            "Tecnólogo(a) em Materiais",
            "Tecnólogo(a) em Mecânica",
            "Tecnólogo(a) em Mecânica - Automobilismo",
            "Tecnólogo(a) em Mecânica - Desenhista Projetista",
            "Tecnólogo(a) em Mecânica - Oficinas",
            "Tecnólogo(a) em Mecânica - Processos Industriais",
            "Tecnólogo(a) em Mecânica - Produção Industrial de Móveis",
            "Tecnólogo(a) em Mecânica - Soldagem",
            "Tecnólogo(a) em Mecânica de Precisão",
            "Tecnólogo(a) em Mecânica, Oficina e Manutenção",
            "Tecnólogo(a) em Mecanização Agrícola",
            "Tecnólogo(a) em Mecatrônica Automotiva",
            "Tecnólogo(a) em Mecatrônica Industrial",
            "Tecnólogo(a) em Metalurgia",
            "Tecnólogo(a) em Meteorologia",
            "Tecnólogo(a) em Microeletrônica",
            "Tecnólogo(a) em Mineração",
            "Tecnólogo(a) em Obras Hidráulicas",
            "Tecnólogo(a) em Operação e Administração de Sistemas de Navegação Fluvial",
            "Tecnólogo(a) em Paisagismo e Jardinagem",
            "Tecnólogo(a) em Pecuária",
            "Tecnólogo(a) em Petróleo e Gás",
            "Tecnólogo(a) em Polímeros",
            "Tecnólogo(a) em Processo de Produção e Usinagem",
            "Tecnólogo(a) em Processos Ambientais",
            "Tecnólogo(a) em Processos Cervejeiros",
            "Tecnólogo(a) em Processos Metalúrgicos",
            "Tecnólogo(a) em Processos Petroquímicos",
            "Tecnólogo(a) em Processos Químicos",
            "Tecnólogo(a) em Produção Cervejeira",
            "Tecnólogo(a) em Produção de Calçados",
            "Tecnólogo(a) em Produção de Cerveja",
            "Tecnólogo(a) em Produção de Couro",
            "Tecnólogo(a) em Produção de Grãos",
            "Tecnólogo(a) em Produção de Petróleo e Gás",
            "Tecnólogo(a) em Produção de Vestuário",
            "Tecnólogo(a) em Produção Industrial",
            "Tecnólogo(a) em Produção Moveleira",
            "Tecnólogo(a) em Produção Sucroalcooleira",
            "Tecnólogo(a) em Produção Têxtil",
            "Tecnólogo(a) em Projeto de Estruturas Aeronáuticas",
            "Tecnólogo(a) em Qualidade Total",
            "Tecnólogo(a) em Química",
            "Tecnólogo(a) em Recursos Hídricos e Irrigação",
            "Tecnólogo(a) em Redes de Computadores",
            "Tecnólogo(a) em Redes de Telecomunicações",
            "Tecnólogo(a) em Refrigeração e Climatização",
            "Tecnólogo(a) em Refrigeração, Ventilação e Ar Condicionado",
            "Tecnólogo(a) em Rochas Ornamentais",
            "Tecnólogo(a) em Saneamento",
            "Tecnólogo(a) em Saneamento Ambiental",
            "Tecnólogo(a) em Saneamento Básico",
            "Tecnólogo(a) em Siderúrgica",
            "Tecnólogo(a) em Silvicultura",
            "Tecnólogo(a) em Sistemas Automotivos",
            "Tecnólogo(a) em Sistemas Biomédicos",
            "Tecnólogo(a) em Sistemas de Comunicação sem Fio",
            "Tecnólogo(a) em Sistemas de Navegação Fluvial",
            "Tecnólogo(a) em Sistemas de Telecomunicações",
            "Tecnólogo(a) em Sistemas de Telefonia",
            "Tecnólogo(a) em Sistemas Elétricos",
            "Tecnólogo(a) em Sistemas Embarcados",
            "Tecnólogo(a) em Soldagem",
            "Tecnólogo(a) em Técnicas Digitais",
            "Tecnólogo(a) em Telecomunicações",
            "Tecnólogo(a) em Telecomunicações - Telefonia e Redes Externas",
            "Tecnólogo(a) em Topografia",
            "Tecnólogo(a) em Transmissão e Distribuição Elétrica",
            "Tecnólogo(a) em Transporte Terrestre",
            "Tecnólogo(a) em Transporte Terrestre - Urbano",
            "Tecnólogo(a) em Viticultura e Enologia",
            "Tecnólogo(a) Industrial de Açúcar de Cana",
            "Tecnólogo(a) Naval",
            "Tecnólogo(a) Sucroalcooleiro",
            "Tecnólogo(a) Têxtil",
            "Urbanista",
        ],
        "conselhos" => [
            0 => "CAU",
            1 => "CONFEA"
        ],
        "situacoes" => [
            0 => "Em análise",
            1 => "Aprovado",
            2 => "Reprovado",
        ],
    ];
